### ISSUE TITLE
基于各个Golang网络库的http响应性能测试

### ISSUE THREAD

**Issue by kiyonlin** [kiyonlin/gonet-benchmarks#1]
这个仓库根据[TFB](https://github.com/TechEmpower/FrameworkBenchmarks)的[plaintext](https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#plaintext)要求，分别实现了基于标准库net，gnet和gev的http纯响应测试代码，即识别每个http请求就立即输出http响应。

目的是想筛选一个包作为一个轻量快速http核心的网络部分基础。

gev的这个issue[#37](https://github.com/Allenxuxu/gev/issues/37)，也可以直接拿目前的代码参加一下TFB。
不过gev有个问题就是不支持Windows系统。

@panjf2000 和 @Allenxuxu 两位有兴趣可以看看代码实现有没有可以优化的地方。

有时间也可以提供一下测试结果供大家参考。

**Comment by korzhao** [comment]
真的是这个结果的话，感觉这两个库 没什么优势啊

**Comment by kiyonlin** [comment]
> 真的是这个结果的话，感觉这两个库 没什么优势啊

你可以自己测试一下，我的测试结果没有覆盖大并发的情况。

**Comment by cch123** [comment]
连接数比较少的话，这种库优势不大

**Comment by lesismal** [comment]
试试我的这个 :smile: 性能应该会比 gnet 略好，实现了 client-side、net.Conn（linux/bsd异步、windows同步），易用性应该也好些：
https://github.com/lesismal/nbio

主要针对linux epoll，mac/bsd下面是epoll但是我没做大规模测，只CI了unit test，windows用的标准库net、日常开发调试和一般项目使用足够了（特殊网络状况时+广播业务类型才可能会有一些影响）
